### ISSUE TITLE
order by using unnest(postal_normalize('address'))

### ISSUE THREAD

**Issue by vlasvlasvlas** [pramsey/pgsql-postal#13]
Hi! 

this is an amazing tool, thanks!

i'm having some issues understanding the order by when my output has multiple rows:

I'm following this great tutorial-blog: https://info.crunchydata.com/blog/quick-and-dirty-address-matching-with-libpostal

This is my example:
`
SELECT unnest(postal_normalize('AV COBO 1122 P 1, CIUDAD AUTONOMA DE BUENOS AIRES, 1406, ARGENTINA')) ;`

And i get:

```
avenida calle cobo 1122 p 1 ciudad autonoma de buenos aires 1406 argentina
avenida calle cobo 1122 planta 1 ciudad autonoma de buenos aires 1406 argentina
avenida calle cobo 1122 paseo 1 ciudad autonoma de buenos aires 1406 argentina
avenida calle cobo 1122 piso 1 ciudad autonoma de buenos aires 1406 argentina
avenida cobo 1122 p 1 ciudad autonoma de buenos aires 1406 argentina
avenida cobo 1122 planta 1 ciudad autonoma de buenos aires 1406 argentina
avenida cobo 1122 paseo 1 ciudad autonoma de buenos aires 1406 argentina
avenida cobo 1122 piso 1 ciudad autonoma de buenos aires 1406 argentina
```

My question: 
Where i can find out the way it "orders by" the output?

thanks!
Vladimiro.

**Comment by pramsey** [comment]
Well, `unnest()` is spooling out the array returned by `postal_normalize()` in the order created and that order... is whatever libpostal happens to provide? I really don't know where the core ordering is coming from. If you want a deterministic order, just do an `ORDER BY` on your unnested results afterwards?

**Comment by vlasvlasvlas** [comment]
ok, 
I'll check out over libpostal issues maybe, and will do the order by on my results. 
Thanks!.

(Been your fan since postgis in action 1st edition :P)
