### ISSUE TITLE
postal.c:46:10: fatal error: 'libpostal/libpostal.h' file not found

### ISSUE THREAD

**Issue by funkonaut** [pramsey/pgsql-postal#15]
Running MacOS 10.15 and postgres 13.1
-Checked that my paths were correctly specified using `pkg-config --cflags --libs libpostal`
-pg_config is on path

As per the suggestion [here](https://stackoverflow.com/questions/63804456/how-to-configure-pg-config-pgxs-make-to-pick-up-cppflags-and-cflags-in-the-makef) Changing CFLAGS_SL to PG_CFLAGS cleared up the issue.

**Comment by pramsey** [comment]
Maybe 105a6ca makes things better.
