### ISSUE TITLE
Is it possible to keep libpostal loaded beyond connections?

### ISSUE THREAD

**Issue by stiivo** [pramsey/pgsql-postal#17]
Hi,
at first, thanks for that great extension.

Because I am not yet so familiar with postgres, I asked myself whether it is possible that the extension is loaded at the start of the postgres daemon and is available for all connections instead of reloading the extension for each connection and thus repeatedly occupying several gb of memory as long as the connection exists.

i hope i have been able to explain my concern in a halfway decent way.

thanks a lot

**Comment by pramsey** [comment]
Each backend (connection) get its own copy.
