### ISSUE TITLE
Install

### ISSUE THREAD

**Issue by gismcieri** [pramsey/pgsql-postal#4]
Hi I am working on learning linux and postgres and I don't get the instructions for installing the library.  I have libpostal working and installed and i have it working for python.  Install postgressql and the contrib packages and i found Pg_config file.  After that i am not sure what to do.  I looked at the makefile for libpostal and i don't see the options in the instructions. Do you happen to have any more detailed instructions.

Thanks,
Matt

**Comment by pramsey** [comment]
Look at the `Makefile` for pgsql-postal, edit the `POSTAL_INCLUDE` and `POSTAL_LIBS` variables to point to your libpostal install location (often `/usr/local` as in the defaults). Check that `pg_config` is in your path by just typing it at the command line. At that point you should be able to just type `make` in the `pgsql-postal` directory and the build should go. It's all in the `README` and I'm not sure how to make it more detailed. I could try automating it, but that would cause as many problems as it solves (using cmake means now... you need cmake).
