### ISSUE TITLE
postal_parse not always returns valid JSON

### ISSUE THREAD

**Issue by linuzer** [pramsey/pgsql-postal#6]
Hi,

while working with your module, I encountered, that the postal_parse function is not always returning a valid JSON object. That is, when the input string contains some special characters, like quotation marks or a backslashes. There might be more, so far I found only those. 
Please consider the related [issue](https://github.com/openvenues/libpostal/issues/140) on the libpostal project and the two examples there that demonstrates the issue.

Best regards.

**Comment by pramsey** [comment]
Should be better at 3dacfed..234c3b6

**Comment by linuzer** [comment]
Great! Thank you very much!
