### ISSUE TITLE
Package for PGXN

### ISSUE THREAD

**Issue by Komzpa** [pramsey/pgsql-postal#7]
Hello, 

Could you please package pgsql-postal for PGXN?

For tiny example, see https://github.com/gojuno/hexgrid-pgsql

**Comment by pramsey** [comment]
I'm not sure I understand what you're requesting. There's a meta.json file for pgxn to consume, beyond that what do you require? Pull request wouldn't hurt...?

**Comment by Komzpa** [comment]
A thing to do is to upload it to pgxn.org, so it can be installed as `sudo pgxn install postal`.

http://manager.pgxn.org/howto

**Comment by pramsey** [comment]
It depends directly on libpostal, a library that approximately nobody is going to have installed. I don't think anyone is going to be able to `sudo pgxn install postal` it. Am I missing some new capability of pgxn?

**Comment by Komzpa** [comment]
It would mean that postgres install instruction will become a mirror of Python install instruction, with just a replacement of `pip` to `pgxn`:
https://github.com/openvenues/pypostal

Or a ruby install instruction, gem -> pgxn:
https://github.com/openvenues/ruby_postal

Or a node install instruction, npm -> pgxn: 
https://github.com/openvenues/node-postal

You have the library in the system after doing any of these, so the rest becomes easier afterwards. Getting it packaged for distros to make the first step easier is another thing, and is likely out of scope of this repo :)

**Comment by pramsey** [comment]
Feel free to upload to pgxn if that makes things better for you.
